server.port=${PORT:8080}
spring.application.name=SmarTech

# DATASOURCE

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/dbsmartech?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true


spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false
spring.web.resources.static-locations=classpath:/static/,classpath:/public/

cloudinary.cloud-name=dmzmm96ff
cloudinary.api-key=324955529673173
cloudinary.api-secret=guuHFnECiOPcPWG8y4YrcnXldok

# Tamaño máximo por archivo
spring.servlet.multipart.max-file-size=20MB

# Tamaño máximo de la petición completa
spring.servlet.multipart.max-request-size=20MB

